DEBUG 2020-05-31 19:30:16.699 UTC: 	 CRAB Client version: 3.3.2005
DEBUG 2020-05-31 19:30:16.700 UTC: 	 Running on: Linux cmslpc151.fnal.gov 3.10.0-1062.12.1.el7.x86_64 #1 SMP Wed Feb 5 09:10:55 CST 2020 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.8 (Nitrogen)
DEBUG 2020-05-31 19:30:16.709 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-05-31 19:30:16.709 UTC: 	 Executing command: 'submit'
DEBUG 2020-05-31 19:30:16.710 UTC: 	 Found CRAB cache file /uscms/home/jluo/.crab3
INFO 2020-05-31 19:30:16.711 UTC: 	 Will use CRAB configuration file crabConfig_HFSim_Global_RAW_cfg.py
DEBUG 2020-05-31 19:30:16.712 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-05-31 19:30:16.714 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-05-31 19:30:16.714 UTC: 	 Working area '/uscms_data/d3/jluo/work/CMSSW_dir/CMSSW_11_1_0_pre6/src/HCALPFG/HcalTupleMaker/test/out_crab/crab_HFSim_Phase2_PU175_Ntuple_new' already exists 
Please change the requestName in the config file
ERROR 2020-05-31 19:30:16.714 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005-bcolbf2/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005-bcolbf2/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005-bcolbf2/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005-bcolbf2/lib/CRABClient/Commands/SubCommand.py", line 323, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005-bcolbf2/lib/CRABClient/ClientUtilities.py", line 407, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/jluo/work/CMSSW_dir/CMSSW_11_1_0_pre6/src/HCALPFG/HcalTupleMaker/test/out_crab/crab_HFSim_Phase2_PU175_Ntuple_new' already exists 
Please change the requestName in the config file
INFO 2020-05-31 19:30:16.719 UTC: 	 Log file is /uscms_data/d3/jluo/work/CMSSW_dir/CMSSW_11_1_0_pre6/src/HCALPFG/HcalTupleMaker/test/crab.log
DEBUG 2020-06-12 15:19:31.466 UTC: 	 CRAB Client version: 3.3.2005
DEBUG 2020-06-12 15:19:31.466 UTC: 	 Running on: Linux cmslpc104.fnal.gov 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 10:44:42 CDT 2020 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.8 (Nitrogen)
DEBUG 2020-06-12 15:19:31.474 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-06-12 15:19:31.475 UTC: 	 Executing command: 'submit'
DEBUG 2020-06-12 15:19:31.475 UTC: 	 Found CRAB cache file /uscms/home/jluo/.crab3
INFO 2020-06-12 15:19:31.477 UTC: 	 Will use CRAB configuration file crabConfig_HFSim_Global_RAW_PU1p2_cfg.py
DEBUG 2020-06-12 15:19:31.477 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-06-12 15:19:31.488 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-06-12 15:19:31.489 UTC: 	 Working area '/uscms_data/d3/jluo/work/CMSSW_dir/CMSSW_11_1_0_pre6/src/HCALPFG/HcalTupleMaker/test/out_crab/crab_HFSim_Phase2_PU1p2_Ntuple_fixed' already exists 
Please change the requestName in the config file
ERROR 2020-06-12 15:19:31.489 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/SubCommand.py", line 323, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/ClientUtilities.py", line 407, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/jluo/work/CMSSW_dir/CMSSW_11_1_0_pre6/src/HCALPFG/HcalTupleMaker/test/out_crab/crab_HFSim_Phase2_PU1p2_Ntuple_fixed' already exists 
Please change the requestName in the config file
INFO 2020-06-12 15:19:31.491 UTC: 	 Log file is /uscms_data/d3/jluo/work/CMSSW_dir/CMSSW_11_1_0_pre6/src/HCALPFG/HcalTupleMaker/test/crab.log
DEBUG 2020-07-13 01:15:49.444 UTC: 	 CRAB Client version: v3.200531
DEBUG 2020-07-13 01:15:49.444 UTC: 	 Running on: Linux cmslpc149.fnal.gov 3.10.0-1127.10.1.el7.x86_64 #1 SMP Tue Jun 2 10:05:57 CDT 2020 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.8 (Nitrogen)
DEBUG 2020-07-13 01:15:49.452 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-07-13 01:15:49.453 UTC: 	 Executing command: 'submit'
DEBUG 2020-07-13 01:15:49.453 UTC: 	 Found CRAB cache file /uscms/home/jluo/.crab3
ERROR 2020-07-13 01:15:49.455 UTC: 	 CRAB configuration file /HFSim_Phase2/jingyu-SingleNeutrino_forHF_RAWSIM_PU100_phase2_noaging-15262e1bc1cd5eefc9db58c6c8a0f318/USER not found.
ERROR 2020-07-13 01:15:49.455 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200531.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200531.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200531.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200531.00/lib/CRABClient/Commands/SubCommand.py", line 319, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200531.00/lib/CRABClient/Commands/SubCommand.py", line 50, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file /HFSim_Phase2/jingyu-SingleNeutrino_forHF_RAWSIM_PU100_phase2_noaging-15262e1bc1cd5eefc9db58c6c8a0f318/USER not found.
INFO 2020-07-13 01:15:49.458 UTC: 	 Log file is /uscms_data/d3/jluo/work/CMSSW_dir/CMSSW_11_1_0_pre6/src/HCALPFG/HcalTupleMaker/test/crab.log
